-- Use this file to run an end to end test

------------------
-- Replace <USERNAME> with your current user
------------------

USE ROLE ACCOUNTADMIN;

GRANT ROLE LOADER TO USER <USERNAME>;
GRANT ROLE TRANSFORMER TO USER <USERNAME>;
GRANT ROLE REPORTER TO USER <USERNAME>;


------------------
-- TEST LOAD
------------------
USE ROLE ROLE_INGEST; 
USE WAREHOUSE WAREHOUSE_INGEST;
CREATE OR REPLACE SCHEMA RAW.SOURCE_NAME;

CREATE TABLE RAW.SOURCE_NAME.MYTABLE (AMOUNT NUMBER);

INSERT INTO MYTABLE VALUES(1);

SELECT * FROM MYTABLE;


------------------
-- TEST TRANSFORM
------------------
USE ROLE ROLE_TRANSFORM; 
USE WAREHOUSE WAREHOUSE_TRANSFORM;
CREATE OR REPLACE SCHEMA ANALYTICS.BUSINESS;

CREATE OR REPLACE TABLE ANALYTICS.BUSINESS.MATERIALISED_TABLE AS (SELECT AMOUNT*2.5 AS SALES_AMOUNT FROM RAW.SOURCE_NAME.MYTABLE);
CREATE OR REPLACE VIEW ANALYTICS.BUSINESS.BUSINESS_VIEW AS (SELECT * FROM MATERIALISED_TABLE);

SELECT * FROM BUSINESS_VIEW;


------------------
-- TEST REPORT
------------------
USE ROLE ROLE_REPORT; 
USE WAREHOUSE WAREHOUSE_REPORT;
USE SCHEMA ANALYTICS.BUSINESS;

SELECT * FROM MATERIALISED_TABLE;
SELECT * FROM BUSINESS_VIEW;

------------------
-- TEST LOAD
------------------
USE ROLE LOADER; 
USE WAREHOUSE LOADING;
CREATE OR REPLACE SCHEMA RAW.SOURCE_NAME;

CREATE TABLE RAW.SOURCE_NAME.MYTABLE (AMOUNT NUMBER);

INSERT INTO MYTABLE VALUES(1);

SELECT * FROM MYTABLE;


------------------
-- TEST TRANSFORM
------------------
USE ROLE TRANSFORMER; 
USE WAREHOUSE TRANSFORMING;
CREATE OR REPLACE SCHEMA ANALYTICS.BUSINESS;

CREATE OR REPLACE TABLE ANALYTICS.BUSINESS.MATERIALISED_TABLE AS (SELECT AMOUNT*2.5 AS SALES_AMOUNT FROM RAW.SOURCE_NAME.MYTABLE);
CREATE OR REPLACE VIEW ANALYTICS.BUSINESS.BUSINESS_VIEW AS (SELECT * FROM MATERIALISED_VIEW);

SELECT * FROM BUSINESS_VIEW;


------------------
-- TEST REPORT
------------------
USE ROLE REPORTER; 
USE WAREHOUSE REPORTING;
USE SCHEMA ANALYTICS.BUSINESS;

SELECT * FROM MATERIALISED_TABLE;
SELECT * FROM BUSINESS_VIEW;
