-- (0) TURN OFF CASE SENSITIVITY
USE ROLE ACCOUNTADMIN;

-- (1) CREATE DATABASES
USE ROLE SYSADMIN;
CREATE DATABASE "RAW";
CREATE DATABASE "ANALYTICS";

-- (2) CREATE WAREHOUSES
CREATE WAREHOUSE "LOADING"
WITH WAREHOUSE_SIZE = 'XSMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1
SCALING_POLICY = 'STANDARD';

CREATE WAREHOUSE "TRANSFORMING"
WITH WAREHOUSE_SIZE = 'XSMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1
SCALING_POLICY = 'STANDARD';

CREATE WAREHOUSE "REPORTING"
WITH WAREHOUSE_SIZE = 'XSMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1
SCALING_POLICY = 'STANDARD';

-- (3) CREATE ROLES AND GRANT PRIVILEGES
USE ROLE ACCOUNTADMIN;

CREATE ROLE "LOADER";
CREATE ROLE "TRANSFORMER";
CREATE ROLE "REPORTER";

GRANT ALL PRIVILEGES ON WAREHOUSE "LOADING" TO ROLE "LOADER";
GRANT ALL PRIVILEGES ON WAREHOUSE "TRANSFORMING" TO ROLE "TRANSFORMER";
GRANT ALL PRIVILEGES ON WAREHOUSE "REPORTING" TO ROLE "REPORTER";

GRANT CREATE SCHEMA, MODIFY, MONITOR, USAGE ON DATABASE "RAW" TO ROLE "LOADER";
GRANT USAGE ON DATABASE "RAW" TO ROLE "LOADER";
GRANT USAGE ON ALL SCHEMAS in DATABASE "RAW" to ROLE "LOADER";
GRANT USAGE ON DATABASE "RAW" TO ROLE "TRANSFORMER";
GRANT USAGE ON ALL SCHEMAS in DATABASE "RAW" to ROLE "TRANSFORMER";

GRANT CREATE SCHEMA, MODIFY, MONITOR, USAGE ON DATABASE "ANALYTICS" TO ROLE "TRANSFORMER";
GRANT USAGE ON DATABASE "ANALYTICS" TO ROLE "TRANSFORMER";
GRANT USAGE ON ALL SCHEMAS in DATABASE "ANALYTICS" to ROLE "TRANSFORMER";
GRANT USAGE ON DATABASE "ANALYTICS" TO ROLE "REPORTER";
GRANT USAGE ON ALL SCHEMAS in DATABASE "ANALYTICS" to ROLE "REPORTER";

-- (4) CREATE USERS
CREATE USER "TEST_REPORTER"
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_ROLE = "REPORTER"
  DEFAULT_WAREHOUSE = "REPORTING"
  PASSWORD = 'PASSWORD'; -- Single quote!
GRANT ROLE "REPORTER" TO USER "TEST_REPORTER";

CREATE USER "TEST_TRANSFORMER"
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_ROLE = "TRANSFORMER"
  DEFAULT_WAREHOUSE = "TRANSFORMING"
  PASSWORD = 'PASSWORD'; -- Single quote!
GRANT ROLE "TRANSFORMER" TO USER "TEST_TRANSFORMER";

CREATE USER "TEST_LOADER"
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_ROLE = "LOADER"
  DEFAULT_WAREHOUSE = "LOADING"
  PASSWORD = 'PASSWORD'; -- Single quote!
GRANT ROLE "LOADER" TO USER "TEST_LOADER";



USE ROLE SYSADMIN;
