-- this file cleans up all objects created in first_run.sql

----------------------------------------
-- DROP ALL OBJECTS
----------------------------------------

USE ROLE SYSADMIN;
DROP DATABASE IF EXISTS "RAW";
DROP DATABASE IF EXISTS "ANALYTICS";
DROP WAREHOUSE IF EXISTS "WAREHOUSE_INGEST";
DROP WAREHOUSE IF EXISTS "WAREHOUSE_TRANSFORM";
DROP WAREHOUSE IF EXISTS "WAREHOUSE_REPORT";

USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS "ROLE_INGEST";
DROP ROLE IF EXISTS "ROLE_TRANSFORM";
DROP ROLE IF EXISTS "ROLE_REPORT";

DROP USER IF EXISTS "USER_INGEST";
DROP USER IF EXISTS "USER_TRANSFORM";
DROP USER IF EXISTS "USER_REPORT";
