-- this file cleans up all objects created in first_run.sql

DROP DATABASE "RAW";
DROP DATABASE "ANALYTICS";
DROP WAREHOUSE "LOADING";
DROP WAREHOUSE "TRANSFORMING";
DROP WAREHOUSE "REPORTING";
DROP ROLE "LOADER";
DROP ROLE "TRANSFORMER";
DROP ROLE "REPORTER";

