-- this file cleans up all objects created in first_run.sql

----------------------------------------
-- DROP ALL OBJECTS
----------------------------------------

USE ROLE SYSADMIN;
DROP DATABASE "RAW";
DROP DATABASE "ANALYTICS";
DROP WAREHOUSE "WAREHOUSE_INGEST";
DROP WAREHOUSE "WAREHOUSE_TRANSFORM";
DROP WAREHOUSE "WAREHOUSE_REPORT";
DROP ROLE "ROLE_INGEST";
DROP ROLE "ROLE_TRANSFORM";
DROP ROLE "ROLE_REPORT";

DROP USER "USER_INGEST";
DROP USER "USER_TRANSFORM";
DROP USER "USER_REPORT";
