-- https://medium.com/hashmapinc/how-to-improve-cloud-cost-monitoring-snowflake-tableau-2aaf6fe2bf2a

-- //==========================================================
-- // create objects
-- //==========================================================


USE ROLE ROLE_DATA_ENGINEERING;
CREATE OR REPLACE VIEW COSTS.SNOWFLAKE_MONITORING.STORAGE_USAGE AS SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE;
CREATE OR REPLACE VIEW COSTS.SNOWFLAKE_MONITORING.WAREHOUSE_USAGE AS SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY;
CREATE OR REPLACE VIEW 
  COSTS.SNOWFLAKE_MONITORING.SNOWFLAKE_USAGE 
AS SELECT 
  TO_TIMESTAMP_NTZ(CONVERT_TIMEZONE('UTC', CASE WHEN (START_TIME IS NULL) THEN USAGE_DATE ELSE START_TIME END)) AS DATE,
  CONVERT_TIMEZONE('UTC',START_TIME) AS START_TIME,
  CONVERT_TIMEZONE('UTC',END_TIME) AS END_TIME,
  STORAGE_BYTES,
  STAGE_BYTES,
  FAILSAFE_BYTES,
  WAREHOUSE_ID,
  WAREHOUSE_NAME,
  CREDITS_USED,
  CREDITS_USED_COMPUTE,
  CREDITS_USED_CLOUD_SERVICES
FROM 
  COSTS.SNOWFLAKE_MONITORING.STORAGE_USAGE A 
FULL OUTER JOIN 
  COSTS.SNOWFLAKE_MONITORING.WAREHOUSE_USAGE B 
ON 
  A.USAGE_DATE = B.START_TIME;
